id: I339BBAA3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T17:38:50+00:00'
last_modified: '2022-06-08T05:54:56.945880+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD19201
  title: རྗེ་དབོན་པདྨ་ཀུན་གྲོལ་རྣམ་རྒྱལ་གྱི་རང་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B949:
      image_group_id: I2PD19215
      title: ''
      total_pages: 160
      order: 1
      base_file: B949.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
